userR/urls.py
from django.urls import path
from .views import signup_view, login_view, logout_view, home_view, create_workout_plan_view, workout_plan_detail, \
    reset_workout_plan

urlpatterns = [
    path('', home_view, name='home'),
    path('signup/', signup_view, name='signup'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('workout-plan/<int:pk>/', workout_plan_detail, name='workout_plan_detail'),
    path('create-workout-plan/', create_workout_plan_view, name='create_workout_plan'),
    path('reset-workout-plan/', reset_workout_plan, name='reset_workout_plan'),
]

worPlan/urls.py
from userR.views import home_view
from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView
)

urlpatterns = [
    path('', include('userR.urls')),
    path('admin/', admin.site.urls),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
]

userR/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models


class MuscleGroup(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Exercise(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    instructions = models.TextField()
    target_muscles = models.ManyToManyField(MuscleGroup, related_name='exercises')

    def __str__(self):
        return self.name





class WorkoutPlan(models.Model):
    LEVEL_CHOICES = [
        ('beginner', 'Beginner'),
        ('intermediate', 'Intermediate'),
        ('hero', 'Hero'),
    ]
    GOAL_CHOICES = [
        ('cut', 'Cut'),
        ('bulk', 'Bulk'),
    ]

    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    workout_frequency = models.IntegerField(
        validators=[
            MinValueValidator(3, "Frequency must be at least 3 day per week"),
            MaxValueValidator(7, "Frequency cannot exceed 7 days per week")
        ]
    )
    workout_goal = models.CharField(max_length=50, choices=GOAL_CHOICES)
    current_level = models.CharField(max_length=50, choices=LEVEL_CHOICES)

    def __str__(self):
        return f"{self.user.username}'s Workout Plan"


class WorkoutDay(models.Model):
    workout_plan = models.ForeignKey(WorkoutPlan, on_delete=models.CASCADE, related_name='workout_days')
    day_number = models.IntegerField()  # or day_name if you prefer names like 'Day 1', 'Day 2', etc.

    def __str__(self):
        return f"{self.workout_plan.user.username}'s Workout Plan: Day {self.day_number}"

class DayExercise(models.Model):
    workout_day = models.ForeignKey(WorkoutDay, on_delete=models.CASCADE, related_name='day_exercises')
    exercise = models.ForeignKey(Exercise, on_delete=models.CASCADE)
    sets = models.IntegerField()
    reps = models.CharField(max_length=10)
    def __str__(self):
        return f"{self.exercise.name} - Sets: {self.sets}, Reps: {self.reps}"

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Registration</title>
    <!-- Include Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <header>
        <!-- Bootstrap navigation bar -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand" href="{% url 'home' %}">Home Page</a>
                <div class="collapse navbar-collapse">
                    <ul class="navbar-nav ml-auto">
                        {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link">Hello {{ user.username }}!</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'logout' %}">Log out</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'login' %}">Log In</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'signup' %}">Sign Up</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main role="main" class="container mt-4">
        {% block content %}
        {% endblock content %}
    </main>
    <!-- Include Bootstrap JS and its dependencies -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

templates/create_workout_plan.html
{% extends 'base.html' %}

{% block content %}
<div class="jumbotron">
    <h1 class="display-4">Few steps are left!</h1>
    {% if user.is_authenticated %}
        <p class="lead">{{ user.username }}, to create a personalized workout plan that fits your goals and current fitness level, we need a few details from you</p>
        <!-- Updated the action to post to the 'create_workout_plan' view -->
        <form method="post" action="{% url 'create_workout_plan' %}">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Create Plan</button>
        </form>
    {% else %}
        <p class="lead">Register to get your own personalized workout plan.</p>
        <a href="{% url 'signup' %}" class="btn btn-primary">Sign Up</a>
    {% endif %}
</div>
{% endblock content %}

templates/home.html
{% extends 'base.html' %}

{% block content %}
<div class="jumbotron">
    {% if user.is_authenticated %}
        {% if workout_plan %}
            <h2>{{ workout_plan.user.username }}'s Workout Plan</h2>
            <p>Frequency: {{ workout_plan.workout_frequency }} days/week</p>
            <p>Goal: {{ workout_plan.get_workout_goal_display }}</p>
            <p>Current Level: {{ workout_plan.get_current_level_display }}</p>
            {% for day in workout_plan.workout_days.all %}
                <h3>Day {{ day.day_number }}</h3>
                <ul>
                    {% for exercise in day.day_exercises.all %}
                        <li>
                            <a href="#" data-toggle="modal" data-target="#exerciseModal{{ exercise.id }}">{{ exercise.exercise.name }}</a>
                            - Sets: {{ exercise.sets }}, Reps: {{ exercise.reps }}
                            <!-- Modal -->
                            <div class="modal fade" id="exerciseModal{{ exercise.id }}" tabindex="-1" role="dialog" aria-labelledby="exerciseModalLabel{{ exercise.id }}" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exerciseModalLabel{{ exercise.id }}">{{ exercise.exercise.name }}</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <p><strong>Description:</strong> {{ exercise.exercise.description }}</p>
                                            <p><strong>Instructions:</strong> {{ exercise.exercise.instructions }}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            {% endfor %}
            <p><a href="{% url 'reset_workout_plan' %}" class="btn btn-warning">Reset My Plan</a></p>
        {% else %}
            <h1 class="display-4">Welcome to our website!</h1>
            <p class="lead">Your adventure starts now.</p>
            <hr class="my-4">
            <p>Explore our features and enjoy your journey.</p>
            <a href="{% url 'create_workout_plan' %}" class="btn btn-primary">Create Workout Plan!</a>
        {% endif %}
    {% else %}
        <h1 class="display-4">Welcome to our website!</h1>
        <p class="lead">Your adventure starts now.</p>
        <hr class="my-4">
        <p>Explore our features and enjoy your journey.</p>
        <p><a href="{% url 'login' %}">Log In</a> or <a href="{% url 'signup' %}">Sign Up</a> to get personalized plan!</p>
    {% endif %}
</div>

<!-- Bootstrap's JavaScript -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
{% endblock %}
    

templates/login.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h2 class="text-center">Login</h2>
        <form method="post" action="{% url 'login' %}" class="mt-3">
            {% csrf_token %}
            <div class="form-group">
                {{ form.as_p }}
            </div>
            <button type="submit" class="btn btn-success btn-block">Log in</button>
        </form>

        {% if error %}
            <div class="alert alert-danger mt-3" role="alert">
                <strong>{{ error }}</strong>
            </div>
        {% endif %}
    </div>
</div>
{% endblock content %}


{#<html>#}
{#<head>#}
{#    <title>User Registration</title>#}
{#</head>#}
{#<body>#}
{#<header>#}
{#    <h1><a href="{% url 'home' %}">Home Page</a></h1>#}
{#</header>#}
{#<div>#}
{#    {% if user.is_authenticated %}#}
{#        <p>Hello {{ user.username }}!</p>#}
{#        <p><a href="{% url 'logout' %}">Log out</a></p>#}
{#    {% else %}#}
{#        <p>Please login.</p>#}
{#        <form method="post" action="{% url 'login' %}">#}
{#            {% csrf_token %}#}
{#            {{ form.as_p }}#}
{#            <button type="submit">Log in</button>#}
{#        </form>#}
{#    {% endif %}#}
{#    {% block content %}#}
{#    {% endblock content %}#}
{#</div>#}
{#</body>#}
{#</html>#}

templates/signup.html
{% extends 'base.html' %}

{% block content %}
    <h2>Sign up</h2>
    <form method="post" class="mt-3">
        {% csrf_token %}
        <div class="form-group">
            {{ form.as_p }}
        </div>
        <button type="submit" class="btn btn-primary">Sign up</button>
    </form>
{% endblock content %}

templates/workout_plan_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="jumbotron">
    <h1 class="display-4">{{ workout_plan.user.username }}'s Workout Plan</h1>
    <p class="lead">Here's a detailed overview of your current workout plan.</p>
    <hr class="my-4">
    <ul class="list-unstyled">
        <li><strong>Frequency:</strong> {{ workout_plan.workout_frequency }} days/week</li>
        <li><strong>Goal:</strong> {{ workout_plan.get_workout_goal_display }}</li>
        <li><strong>Current Level:</strong> {{ workout_plan.get_current_level_display }}</li>
    </ul>

    {% for day in workout_days %}
        <div>
            <h3>Day {{ day.day_number }}</h3>
            <ul>
                {% for exercise in day.day_exercises.all %}
                    <li>
                        <a href="#" data-toggle="modal" data-target="#exerciseModal{{ exercise.id }}">{{ exercise.exercise.name }}</a>
                        - Sets: {{ exercise.sets }}, Reps: {{ exercise.reps }}
                        <!-- Modal -->
                        <div class="modal fade" id="exerciseModal{{ exercise.id }}" tabindex="-1" role="dialog" aria-labelledby="exerciseModalLabel{{ exercise.id }}" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exerciseModalLabel{{ exercise.id }}">{{ exercise.exercise.name }}</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <p><strong>Description:</strong> {{ exercise.exercise.description }}</p>
                                        <p><strong>Instructions:</strong> {{ exercise.exercise.instructions }}</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>
    {% endfor %}
</div>

<!-- Bootstrap's JavaScript -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
{% endblock %}